/**
 * Turns one of the app's bundled legal documents into a Markdown page of the
 * documentation site.
 *
 * The hosted page and the in-app screen have to say the same thing, so both
 * are rendered from `src/app/content/`. Nothing here adds wording of its own:
 * the page is the document, laid out for the site to style.
 *
 * @format
 */

const MONTH_NAMES = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

/**
 * Escape text so Markdown renders it as written.
 *
 * @param {string} text - Text taken from the document.
 * @returns {string} The same text, with every character that could start
 *   Markdown or HTML syntax escaped.
 */
const escapeMarkdown = text =>
  String(text)
    .replace(/&/g, '&amp;')
    .replace(/[\\`*_[\]<>{}]/g, character => `\\${character}`);

/**
 * Spell out an ISO date the way the page shows it.
 *
 * @param {string} isoDate - Date as `YYYY-MM-DD`, from the document.
 * @returns {string} The date as `25 August 2026`, or the input unchanged when
 *   it is not in that form.
 */
const formatDate = isoDate => {
  const parts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(isoDate);
  if (!parts) return isoDate;
  const [, year, month, day] = parts;
  return `${Number(day)} ${MONTH_NAMES[Number(month) - 1]} ${year}`;
};

/**
 * Render the highlighted note a document opens with as a note aside.
 *
 * @param {{title: string, content: string}} banner - One banner of the document.
 * @returns {string} Its Markdown.
 */
const renderBanner = banner =>
  `:::note[${escapeMarkdown(banner.title)}]\n${escapeMarkdown(
    banner.content,
  )}\n:::`;

/**
 * Render one point within a section as a list item.
 *
 * @param {{title: string, description?: string|null}} item - One item of a section.
 * @returns {string} Its Markdown.
 */
const renderItem = item => {
  const title = `- **${escapeMarkdown(item.title)}**`;
  if (!item.description) return title;
  return `${title}\n\n  ${escapeMarkdown(item.description)}`;
};

/**
 * Render one section of a document, with its points.
 *
 * @param {{title: string, description?: string|null, items: Array<object>}} section
 *   One section of the document.
 * @returns {string} Its Markdown.
 */
const renderSection = section => {
  const parts = [`## ${escapeMarkdown(section.title)}`];
  if (section.description) parts.push(escapeMarkdown(section.description));
  if (section.items.length) parts.push(section.items.map(renderItem).join('\n\n'));
  return parts.join('\n\n');
};

/**
 * Render a bundled legal document as a complete Markdown page.
 *
 * @param {{title: string, last_updated: string, banners: Array<object>, sections: Array<object>}} document
 *   A document from `src/app/content/`.
 * @param {string} productName - The app the document belongs to.
 * @param {string} sourcePath - Where the document comes from, named in the
 *   page so nobody edits the generated file.
 * @returns {string} The whole page, ending in a newline.
 */
const renderMarkdownPage = (document, productName, sourcePath) => {
  const updated = formatDate(document.last_updated);
  const description = `The ${document.title} for ${productName}, last updated ${updated}.`;
  return [
    '---',
    `title: ${JSON.stringify(document.title)}`,
    `description: ${JSON.stringify(description)}`,
    '---',
    '',
    `<!-- Generated by scripts/render-pages.js from ${sourcePath}. Do not edit: run \`npm run pages:render\`. -->`,
    '',
    `Last updated <time datetime="${escapeMarkdown(
      document.last_updated,
    )}">${escapeMarkdown(updated)}</time>`,
    '',
    ...document.banners.map(banner => `${renderBanner(banner)}\n`),
    ...document.sections.map(section => `${renderSection(section)}\n`),
    `This page carries the same text as the ${escapeMarkdown(
      document.title,
    )} screen inside ${escapeMarkdown(productName)}.`,
    '',
  ].join('\n');
};

module.exports = { renderMarkdownPage };
